In [1]:
import numpy as np
from scipy import linalg

def perform_svd(matrix):
    
    m, n = matrix.shape
    
    A = matrix
    print("Here's your original matrix:")
    print(A.__str__())
    print()
    
    U, s, Vt = linalg.svd(A)
    
    if m == n:
        Sigma = np.diag(s)
    elif m > n:
        Sigma = np.zeros((m, n))
        Sigma[:n, :n] = np.diag(s)
    else:
        Sigma = np.zeros((m, n))
        Sigma[:m, :m] = np.diag(s)
           
    print("Please hold.... Numpy is performing some magic")
    print(".......")
    print("Ok Numpy is ready for you")
    print()
    
    print("Here is U:")
    print(np.round(U, 4).__str__())
    print()
    
    print("Here is Σ:")
    print(np.round(Sigma, 4).__str__())
    print()
    
    print("Here is Vt:")
    print(np.round(Vt, 4).__str__())
    print()
    
    print("Ok, now that Numpy took your nice matrix apart, we're going to put it back together")
    print("Please hold one more time!")
    print(".........")
    print(".........")
    print("OK DONE!")
    
    B = U.dot(Sigma.dot(Vt))
    print()
    print(np.round(B, 0).__str__())

In [2]:
A = np.array([[1, 1, 0], [0, 1, -1]])
perform_svd(A)

Here's your original matrix:
[[ 1  1  0]
 [ 0  1 -1]]

Please hold.... Numpy is performing some magic
.......
Ok Numpy is ready for you

Here is U:
[[-0.7071 -0.7071]
 [-0.7071  0.7071]]

Here is Σ:
[[1.7321 0.     0.    ]
 [0.     1.     0.    ]]

Here is Vt:
[[-0.4082 -0.8165  0.4082]
 [-0.7071  0.     -0.7071]
 [-0.5774  0.5774  0.5774]]

Ok, now that Numpy took your nice matrix apart, we're going to put it back together
Please hold one more time!
.........
.........
OK DONE!

[[ 1.  1.  0.]
 [ 0.  1. -1.]]


In [3]:
B = np.array([[2, 1], [1, 2]])
perform_svd(B)

Here's your original matrix:
[[2 1]
 [1 2]]

Please hold.... Numpy is performing some magic
.......
Ok Numpy is ready for you

Here is U:
[[-0.7071 -0.7071]
 [-0.7071  0.7071]]

Here is Σ:
[[3. 0.]
 [0. 1.]]

Here is Vt:
[[-0.7071 -0.7071]
 [-0.7071  0.7071]]

Ok, now that Numpy took your nice matrix apart, we're going to put it back together
Please hold one more time!
.........
.........
OK DONE!

[[2. 1.]
 [1. 2.]]


In [4]:
C = np.array([[7, 2], [3, 4], [5, 3]])
perform_svd(C)

Here's your original matrix:
[[7 2]
 [3 4]
 [5 3]]

Please hold.... Numpy is performing some magic
.......
Ok Numpy is ready for you

Here is U:
[[-0.6937  0.5934 -0.4082]
 [-0.4427 -0.7983 -0.4082]
 [-0.5682 -0.1025  0.8165]]

Here is Σ:
[[10.2514  0.    ]
 [ 0.      2.6284]
 [ 0.      0.    ]]

Here is Vt:
[[-0.8803 -0.4743]
 [ 0.4743 -0.8803]]

Ok, now that Numpy took your nice matrix apart, we're going to put it back together
Please hold one more time!
.........
.........
OK DONE!

[[7. 2.]
 [3. 4.]
 [5. 3.]]


In [5]:
D = np.array([[1,2,3,4,5,6],
              [11,12,13,14,15,16],
              [21,22,23,24,25,26]])
perform_svd(D)

Here's your original matrix:
[[ 1  2  3  4  5  6]
 [11 12 13 14 15 16]
 [21 22 23 24 25 26]]

Please hold.... Numpy is performing some magic
.......
Ok Numpy is ready for you

Here is U:
[[-0.1327  0.9032  0.4082]
 [-0.4956  0.2962 -0.8165]
 [-0.8584 -0.3107  0.4082]]

Here is Σ:
[[67.2239  0.      0.      0.      0.      0.    ]
 [ 0.      3.7338  0.      0.      0.      0.    ]
 [ 0.      0.      0.      0.      0.      0.    ]]

Here is Vt:
[[-0.3512 -0.3733 -0.3954 -0.4176 -0.4397 -0.4618]
 [-0.6328 -0.3948 -0.1568  0.0812  0.3193  0.5573]
 [-0.3676 -0.2019  0.5264  0.4645  0.1375 -0.5589]
 [-0.0908  0.2595 -0.5937  0.7164 -0.2356 -0.0558]
 [-0.2297  0.4741 -0.2993 -0.2577  0.665  -0.3525]
 [-0.5292  0.6098  0.316  -0.1538 -0.4337  0.1909]]

Ok, now that Numpy took your nice matrix apart, we're going to put it back together
Please hold one more time!
.........
.........
OK DONE!

[[ 1.  2.  3.  4.  5.  6.]
 [11. 12. 13. 14. 15. 16.]
 [21. 22. 23. 24. 25. 26.]]
