In [ ]:
In [1]: final_results('teams.csv','winloss.csv')
Out[1]:
(array(['Rams', 'Cubs', 'Jazz', 'Owls', 'Jets', 'Zips'],
dtype='<U4'), array([4, 3, 3, 2, 2, 1]))

In [89]:
import numpy as np

def final_results(teams, win_loss):
    teams = np.loadtxt(teams, delimiter = ",", dtype = str)
    win_loss = np.loadtxt(win_loss, delimiter = ",", dtype = str)
    
    win_loss = np.sum(np.where(win_loss == 'W', 1, 0), axis = 1)
    
    return teams[np.argsort(win_loss)[::-1]], win_loss[np.argsort(win_loss)[::-1]]

In [90]:
final_results("teams.csv", "winloss.csv")

(array(['Rams', 'Cubs', 'Jazz', 'Owls', 'Jets', 'Zips'], dtype='<U4'),
 array([4, 3, 3, 2, 2, 1]))

In [3]:
win_loss

array([['X', 'W', 'W', 'L', 'L', 'W'],
       ['L', 'X', 'W', 'W', 'L', 'L'],
       ['L', 'L', 'X', 'L', 'W', 'W'],
       ['W', 'L', 'W', 'X', 'W', 'W'],
       ['W', 'W', 'L', 'L', 'X', 'W'],
       ['L', 'W', 'L', 'L', 'L', 'X']], dtype='<U1')

In [4]:
a = np.sum(np.where(win_loss == 'W', 1, 0), axis = 1)

In [22]:
(teams, a)

(array(['Jazz', 'Jets', 'Owls', 'Rams', 'Cubs', 'Zips'], dtype='<U4'),
 array([3, 2, 2, 4, 3, 1]))

In [25]:
teams[np.argsort(-a)], a[np.argsort(-a)]

(array(['Rams', 'Jazz', 'Cubs', 'Jets', 'Owls', 'Zips'], dtype='<U4'),
 array([4, 3, 3, 2, 2, 1]))

In [41]:
np.argsort(a)

array([5, 1, 2, 0, 4, 3], dtype=int64)

In [88]:
teams[np.argsort(a)[::-1]], a[np.argsort(a)[::-1]]

(array(['Rams', 'Cubs', 'Jazz', 'Owls', 'Jets', 'Zips'], dtype='<U4'),
 array([4, 3, 3, 2, 2, 1]))

In [82]:
np.sort(a)[::-1]

array([4, 3, 3, 2, 2, 1])

array(['Zips', 'Rams', 'Owls', 'Jets', 'Jazz', 'Cubs'], dtype='<U4')

In [62]:
np.argsort(A, axis=1)[:, ::-1]

TypeError: tuple() takes at most 1 argument (2 given)