In [3]:
import numpy as np

In [ ]:
In [1]: inventory = [[25,64,23],[30,82,19]]
In [2]: sales = [[7,45,11],[4,24,8]]
In [3]: final_inventory(inventory,sales)
Out[3]:
array([[18, 19, 12],
[26, 58, 11]])

In [1]:
inventory = [[25,64,23],[30,82,19]]

In [2]:
sales = [[7,45,11],[4,24,8]]

In [4]:
def final_inventory(inventory, sales):
    inventory = np.array(invertory)
    sales = np.array(sales)
    return inventory - sales

In [6]:
inventory = [[25,64,23],[30,82,19]]
sales = [[7,45,11],[4,24,8]]

def final_inventory(inventory, sales):
    inventory = np.array(inventory)
    sales = np.array(sales)
    return inventory - sales

final_inventory(inventory, sales)

array([[18, 19, 12],
       [26, 58, 11]])

In [7]:
inventory = [[25,64,23],[30,82,19]]
sales = [[7,45,11],[4,24,8]]

def final_inventory(inventory, sales):
    return np.array(inventory) - np.array(sales)

final_inventory(inventory, sales)

array([[18, 19, 12],
       [26, 58, 11]])