## Numpy Basics Refresher

In [3]:
import numpy as np

In [4]:
data1 = [6, 7.5, 8, 0, 1]

In [5]:
arr1 = np.array(data1)

In [6]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [7]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [8]:
arr2 = np.array(data2)

In [9]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
arr2.ndim

2

In [14]:
arr2.shape

(2, 4)

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
np.empty((2, 3, 2))

array([[[8.13820328e-312, 2.86558075e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 8.75983079e+164]],

       [[6.56449301e-091, 1.80194451e+185],
        [8.40869493e+164, 1.45256411e+165],
        [6.48224659e+170, 5.82471487e+257]]])

In [18]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [30]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [31]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [32]:
numeric_strings =np.array(['1.25', '-9.6', '42'], dtype = np.string_)

In [33]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [35]:
int_array = np.arange(10)

In [36]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype = np.float64)

In [37]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [38]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [39]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [40]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [41]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [43]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [44]:
arr = np.arange(10)

In [45]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
arr[5]

5

In [47]:
arr[5:8]

array([5, 6, 7])

In [48]:
arr[5:8] = 12

In [49]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [50]:
arr_slice = arr[5:8]

In [51]:
arr_slice[1] = 12345

In [52]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [53]:
arr_slice[:] = 64

In [54]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [55]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [57]:
arr2d[0][2]

3

In [58]:
arr2d[0, 2]

3

In [59]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [60]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [61]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
old_values = arr3d[0].copy()

In [63]:
arr3d[0] = 42

In [64]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [65]:
arr3d[0] = old_values

In [67]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [68]:
arr3d[1, 0]

array([7, 8, 9])

In [69]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [70]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
# up to the second row :2, from the second column on 1:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [78]:
arr2d[1, :2]

array([4, 5])

In [79]:
arr2d[2, :1]

array([7])

In [80]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [87]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [83]:
data = np.random.randn(7, 4)

In [88]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [85]:
data

array([[-1.26611257e+00,  3.61215126e-01, -4.70519741e-01,
         1.22303699e+00],
       [ 8.57096944e-01, -6.41624913e-01, -1.06147154e+00,
         3.93710649e-01],
       [-5.48451896e-01,  1.02505137e+00,  1.23780784e+00,
         1.27305715e+00],
       [-1.67879708e-01, -1.59464454e-03, -1.18681775e+00,
         9.62137454e-01],
       [-1.57837788e+00,  1.27633093e-01,  4.09444482e-01,
        -3.36252358e-01],
       [ 2.50222277e-01, -1.76870178e+00,  9.93706848e-01,
        -8.30265274e-01],
       [ 2.73351445e-01,  4.51604651e-01, -7.76661036e-01,
        -8.89288809e-01]])

In [89]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [90]:
data[names == 'Bob']

array([[-1.26611257,  0.36121513, -0.47051974,  1.22303699],
       [-0.16787971, -0.00159464, -1.18681775,  0.96213745]])

In [91]:
data[names == 'Bob', 3]

array([1.22303699, 0.96213745])

In [92]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [94]:
data[~(names == 'Bob')]

array([[ 0.85709694, -0.64162491, -1.06147154,  0.39371065],
       [-0.5484519 ,  1.02505137,  1.23780784,  1.27305715],
       [-1.57837788,  0.12763309,  0.40944448, -0.33625236],
       [ 0.25022228, -1.76870178,  0.99370685, -0.83026527],
       [ 0.27335144,  0.45160465, -0.77666104, -0.88928881]])

In [95]:
mask = (names == 'Bob') | (names == 'Will')

In [96]:
mask

array([ True, False,  True,  True,  True, False, False])

In [97]:
data[mask]

array([[-1.26611257,  0.36121513, -0.47051974,  1.22303699],
       [-0.5484519 ,  1.02505137,  1.23780784,  1.27305715],
       [-0.16787971, -0.00159464, -1.18681775,  0.96213745],
       [-1.57837788,  0.12763309,  0.40944448, -0.33625236]])

In [98]:
data[data < 0] = 0

In [99]:
data

array([[0.        , 0.36121513, 0.        , 1.22303699],
       [0.85709694, 0.        , 0.        , 0.39371065],
       [0.        , 1.02505137, 1.23780784, 1.27305715],
       [0.        , 0.        , 0.        , 0.96213745],
       [0.        , 0.12763309, 0.40944448, 0.        ],
       [0.25022228, 0.        , 0.99370685, 0.        ],
       [0.27335144, 0.45160465, 0.        , 0.        ]])

In [100]:
data[names != 'Joe'] = 7

In [101]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.85709694, 0.        , 0.        , 0.39371065],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.25022228, 0.        , 0.99370685, 0.        ],
       [0.27335144, 0.45160465, 0.        , 0.        ]])

In [102]:
arr = np.empty((8, 4))

In [104]:
for i in range(8):
    arr[i] = i

In [105]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [106]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [107]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [108]:
arr = np.arange(32).reshape((8, 4))

In [109]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [110]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [111]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [112]:
arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [113]:
arr = np.arange(15).reshape((3, 5))

In [114]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [115]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [116]:
arr = np.random.randn(6, 3)

In [117]:
np.dot(arr.T, arr)

array([[ 5.87591008, -6.14496665,  2.76799   ],
       [-6.14496665,  9.28553229, -3.10499166],
       [ 2.76799   , -3.10499166,  6.9382146 ]])

In [118]:
arr = np.arange(16).reshape((2, 2, 4))

In [119]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [120]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [121]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [122]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [123]:
arr = np.arange(10)

In [124]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [125]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [126]:
x = np.random.randn(8)

In [127]:
y = np.random.randn(8)

In [128]:
x

array([ 1.20006207,  0.025849  ,  0.51057151,  0.6414094 , -0.57092686,
        0.26291694,  0.16998468,  0.2781407 ])

In [129]:
y

array([ 2.26901625, -0.22137883, -1.60837717,  1.45369032, -0.53216917,
        0.58434082,  1.24702078, -0.45143493])

In [130]:
np.maximum(x, y)

array([ 2.26901625,  0.025849  ,  0.51057151,  1.45369032, -0.53216917,
        0.58434082,  1.24702078,  0.2781407 ])

In [131]:
arr = np.random.randn(7) * 5

In [132]:
np.modf(arr)

(array([ 0.60288085,  0.18690154,  0.45831163, -0.06820631,  0.0133234 ,
         0.7216313 , -0.77691661]), array([ 3., 10.,  0., -5.,  1.,  0., -4.]))

In [135]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])

In [136]:
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [137]:
cond = np.array([True, False, True, True, False])

In [138]:
result = [(x if c else y)
         for x, y, c in zip(xarr, yarr, cond)]

In [139]:
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [140]:
result = np.where(cond, xarr, yarr)

In [141]:
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [142]:
arr = np.random.randn(4, 4)

In [143]:
arr

array([[ 0.53868715,  1.18258906, -1.12058845, -1.09682593],
       [-0.50345557, -0.49856968, -0.84579141, -0.2737159 ],
       [ 0.60324462,  0.05984254, -0.04054244, -0.93030087],
       [-0.0564806 , -1.3943864 ,  0.23568407, -0.63007769]])

In [144]:
np.where(arr > 0, 2, -2)

array([[ 2,  2, -2, -2],
       [-2, -2, -2, -2],
       [ 2,  2, -2, -2],
       [-2, -2,  2, -2]])

In [145]:
np.where(arr > 0, 2, arr)

array([[ 2.        ,  2.        , -1.12058845, -1.09682593],
       [-0.50345557, -0.49856968, -0.84579141, -0.2737159 ],
       [ 2.        ,  2.        , -0.04054244, -0.93030087],
       [-0.0564806 , -1.3943864 ,  2.        , -0.63007769]])

In [147]:
result = []
for i in range(5):
    if cond1[i] and cond2[i]:
        result.append(0)
    elif cond1[i]:
        result.append(1)
    elif cond2[i]:
        result.append(2)
    else:
        result.append(3)

NameError: name 'cond1' is not defined

In [148]:
np.where(cond1 & cond2, 0
        np.where(cond1, 1,
                np.where(cond2, 2, 3)))

SyntaxError: invalid syntax (<ipython-input-148-8847eaaae011>, line 2)

In [149]:
result = 1 * cond1 + 2 * cond2 + 3 * -(cond1 | cond2)

NameError: name 'cond1' is not defined