In [1]:
def B(x1):
    if x1 == '':
        return x1
    else:
        return B(x1[1:]) + x1[0]

In [17]:
B('10000000000')

'00000000001'

In [9]:
class Employee:
    """Empty class to represent an Employee"""
    
emp1 = Employee()
emp1.name = 'Alice'

emp2 = Employee()
emp2.name = 'Bob'

emp2 = emp1

emp2.name = 'Robert'

In [22]:
a = [emp1, '1']

In [23]:
a

[<__main__.Employee at 0x25c79f1bcf8>, '1']

In [14]:
class fewadfsaf:

SyntaxError: unexpected EOF while parsing (<ipython-input-14-908c8ad795d0>, line 1)

In [24]:
import numpy as np

In [54]:
a = np.array([[20, 11, 6, 11], [ 2, 14, 10, 11], [ 9, 20, 1, 14], [ 1, 7, 1, 6]])

In [29]:
a.mean()

9.0

In [30]:
a.sum(0)

array([32, 52, 18, 42])

In [31]:
a.max(1)

array([20, 14, 20,  7])

In [32]:
a.min()

1

In [33]:
a.mean(0)

array([ 8. , 13. ,  4.5, 10.5])

In [56]:
a

array([[20, 11,  6, 11],
       [ 2, 14, 10, 11],
       [ 9, 20,  1, 14],
       [ 1,  7,  1,  6]])

In [52]:
np.cos(a)

TypeError: 'tuple' object is not callable

In [38]:
np.ones([3, 2]).shape()

TypeError: 'tuple' object is not callable

In [36]:
np.ones(2, 3)

TypeError: data type not understood

In [42]:
y = [6, 2, 1, 0, 0]
z = [6, 2, 5, 2, 9]

In [43]:
np.where([1,1,0,1,1])

(array([0, 1, 3, 4], dtype=int64),)

In [47]:
a  = np.array([[ 6, 6, 15, 16], [16, 3, 6, 11], [ 5, 18, 20, 18], [ 8, 3, 10, 7]])

In [48]:
a.sort()

In [49]:
a

array([[ 6,  6, 15, 16],
       [ 3,  6, 11, 16],
       [ 5, 18, 18, 20],
       [ 3,  7,  8, 10]])

In [51]:
a = np.array([[ 6, 28, 21, 10, 13] [ 6, 26, 8, 28, 19] [13, 4, 28, 8, 19] [ 4, 29, 24, 27, 20]])

TypeError: list indices must be integers or slices, not tuple