In [ ]:
In [1]: rankings_for('ranking.txt','stanford')
Out[1]:
array(['Education', 'Engineering', 'Law'],
dtype='<U11')
In [2]: rankings_for('ranking.txt','iowa')
Out[2]: array([], dtype=float64)

In [2]:
import numpy as np

In [54]:
rankings_for = np.loadtxt("ranking.txt", delimiter = ",", dtype = str)

In [53]:
for i in rankings_for:
    print(i)

['Education' 'Vanderbilt' 'Harvard' 'U of Texas' 'Stanford' 'Columbia']
['Engineering' 'MIT' 'Stanford' 'UC Berk' 'GA Tech' 'Cal Tech']
['Law' 'Yale' 'Stanford' 'Harvard' 'Columbia' 'U of Chicago']


In [82]:
rankings_for == 'Stanford'

array([[False, False, False, False,  True, False],
       [False, False,  True, False, False, False],
       [False, False,  True, False, False, False]])

In [41]:
college = "Stanford"


rankings_for[np.where(rankings_for[rankings_for == "Stanford"])][:, 0]

array(['Education', 'Engineering', 'Law'], dtype='<U12')

In [90]:
lower = np.array([[word.lower() for word in i] for i in rankings_for.tolist()])

In [97]:
rankings_for[lower == 'stanford']

array(['Stanford', 'Stanford', 'Stanford'], dtype='<U12')

In [1]:
import numpy as np

def rankings_for(filename, school):
    rankings = np.loadtxt(filename, delimiter = ",", dtype = str)
    lower = np.array([[word.lower() for word in i] for i in rankings.tolist()])
    return rankings[np.where(rankings[lower == school.lower()])][:, 0]

In [2]:
rankings = np.loadtxt("ranking.txt", delimiter = ",", dtype = str)

In [11]:
rankings[np.where(rankings[lower == 'stanford'.lower()])

array(['Education', 'Engineering', 'Law'], dtype='<U12')

In [3]:
rankings

array([['Education', 'Vanderbilt', 'Harvard', 'U of Texas', 'Stanford',
        'Columbia'],
       ['Engineering', 'MIT', 'Stanford', 'UC Berk', 'GA Tech',
        'Cal Tech'],
       ['Law', 'Yale', 'Stanford', 'Harvard', 'Columbia', 'U of Chicago']],
      dtype='<U12')

In [4]:
lower = np.array([[word.lower() for word in i] for i in rankings.tolist()])

In [5]:
lower

array([['education', 'vanderbilt', 'harvard', 'u of texas', 'stanford',
        'columbia'],
       ['engineering', 'mit', 'stanford', 'uc berk', 'ga tech',
        'cal tech'],
       ['law', 'yale', 'stanford', 'harvard', 'columbia', 'u of chicago']],
      dtype='<U12')

In [102]:
rankings_for("ranking.txt", "stanford")

array(['Education', 'Engineering', 'Law'], dtype='<U12')

In [105]:
rankings_for("ranking.txt", "Minnesota")

array([], dtype='<U12')

In [16]:
rankings = np.loadtxt("ranking.txt", delimiter = ",", dtype = str)

In [11]:
subjects = rankings[:, 0:1]

In [24]:
schools = np.char.lower(rankings[:, 1:])

In [32]:
x = "Stanford"
subjects[np.where(schools[schools == x.lower()])]

array([['Education'],
       ['Engineering'],
       ['Law']], dtype='<U12')

In [276]:
import numpy as np

def rankings_for(filename, school):
    rankings = np.loadtxt(filename, delimiter = ",", dtype = str)
    return rankings[np.any(np.char.lower(rankings) == school.lower(), axis = 1), :1].flatten()

In [277]:
rankings_for('ranking.txt', 'harvard')

array(['Education', 'Law'], dtype='<U12')

In [271]:
rankings = np.loadtxt('ranking.txt', delimiter = ",", dtype = str)

In [275]:
np.char.lower(rankings) == 'harvard'

array([[False, False,  True, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False,  True, False, False]])

In [249]:
subjects = rankings[:, 0:1]
schools = rankings[:, 1:]

In [255]:
subjects[np.any(schools == "harvard".capitalize(), axis = 1)].flatten()

array(['Education', 'Law'], dtype='<U12')

In [ ]:
rankings[np.any(rows, axis = 1)]

In [262]:
rankings[np.any(schools == "harvard".capitalize(), axis = 1),:1].flatten()

array(['Education', 'Law'], dtype='<U12')

In [191]:
`schools == "harvard".capitalize()

array([[False,  True, False, False, False],
       [False, False, False, False, False],
       [False, False,  True, False, False]])

In [190]:
schools

array([['Vanderbilt', 'Harvard', 'U of Texas', 'Stanford', 'Columbia'],
       ['MIT', 'Stanford', 'UC Berk', 'GA Tech', 'Cal Tech'],
       ['Yale', 'Stanford', 'Harvard', 'Columbia', 'U of Chicago']],
      dtype='<U12')

In [234]:
rows = rankings == 'columbia'.capitalize()

In [201]:
np.sum(np.where(rankings == 'columbia'.capitalize(), 1, 0), axis = 1)

array([1, 0, 1])

In [241]:
rankings[np.any(rows, axis = 1)]

array([['Education', 'Vanderbilt', 'Harvard', 'U of Texas', 'Stanford',
        'Columbia'],
       ['Law', 'Yale', 'Stanford', 'Harvard', 'Columbia', 'U of Chicago']],
      dtype='<U12')

In [179]:
rankings[np.ix_(rankings[rankings == 'columbia'.capitalize()], np.array([True, False, False]))]

IndexError: arrays used as indices must be of integer (or boolean) type

In [76]:
rankings[np.where(rankings == 'stanford'.capitalize())]

array(['Stanford', 'Stanford', 'Stanford'], dtype='<U12')

In [ ]:
np.intersect1d

In [ ]:
subjects = rankings[:, 0:1]
schools = np.char.lower(rankings[:, 1:])

In [51]:
rankings_for("ranking.txt", "iowa")

array([], dtype='<U12')