In [ ]:
pct_change('degrees.txt')
Out[1]:
(array(['Computer Science', 'Business', 'Social Sciences', 'Engineering',
'Education'],
dtype='<U16'),
array([ 161.8146948 , 78.6810359 , 71.89816243, 14.16046007,
-6.30031275]))

In [112]:
import numpy as np

def pct_change(filename):
    degrees = np.loadtxt(filename, delimiter = ",", dtype = str)
    
    school = degrees[:, 0:1]
    start = degrees[:, 1:2].astype(int)
    end = degrees[:, 2:3].astype(int)
    
    percent_change = (end - start) / start * 100
    
    return school[np.argsort(percent_change, axis = 0)[::-1]].flatten(), percent_change[np.argsort(percent_change, axis = 0)[::-1]].flatten()

In [113]:
pct_change("degrees.txt")

(array(['Computer Science', 'Business', 'Social Sciences', 'Engineering',
        'Education'], dtype='<U16'),
 array([161.8146948 ,  78.6810359 ,  71.89816243,  14.16046007,
         -6.30031275]))

In [102]:
degrees = np.loadtxt("degrees.txt", delimiter = ",", dtype = str)

In [103]:
school = degrees[:, 0:1]

In [104]:
start = degrees[:, 1:2].astype(int)

In [105]:
end = degrees[:, 2:3].astype(int)

In [99]:
percent_change = (end - start) / start * 100

In [108]:
school[np.argsort(percent_change, axis = 0)[::-1]].flatten(), percent_change[np.argsort(percent_change, axis = 0)[::-1]].flatten()

(array(['Computer Science', 'Business', 'Social Sciences', 'Engineering',
        'Education'], dtype='<U16'),
 array([161.8146948 ,  78.6810359 ,  71.89816243,  14.16046007,
         -6.30031275]))

In [90]:
degrees

array([['Business', '200521', '358293'],
       ['Computer Science', '15121', '39589'],
       ['Education', '108074', '101265'],
       ['Engineering', '63642', '72654'],
       ['Social Sciences', '100513', '172780']], dtype='<U16')

In [35]:
percentage_change = (degrees[:, 2:3].astype(int) - degrees[:, 1:2].astype(int)) / degrees[:, 1:2].astype(int) * 100

In [63]:
degrees[:, 0:1][np.argsort(percentage_change, axis = 0)[::-1]]

array([[['Computer Science']],

       [['Business']],

       [['Social Sciences']],

       [['Engineering']],

       [['Education']]], dtype='<U16')

In [64]:
percentage_change

array([[ 78.6810359 ],
       [161.8146948 ],
       [ -6.30031275],
       [ 14.16046007],
       [ 71.89816243]])